# Generated by Django 4.1.5 on 2023-03-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsContent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
