# Generated by Django 4.1.5 on 2023-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsContent', '0002_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
