# Generated by Django 4.1.5 on 2023-03-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsContent', '0003_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
