# Generated by Django 4.1.5 on 2023-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsContent', '0004_remove_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='etst'),
            preserve_default=False,
        ),
    ]
