# Generated by Django 4.1.5 on 2023-03-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsContent', '0005_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='shoe_size',
            name='model',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='productsContent.products'),
            preserve_default=False,
        ),
    ]
