# Generated by Django 4.1.5 on 2023-02-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
