# Generated by Django 4.1.5 on 2023-02-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp1', '0002_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=20)),
                ('shoe_size', models.CharField(choices=[(40, 40), (42, 42), (41, 41), (43, 43), (44, 44)], max_length=1)),
            ],
        ),
    ]
