# Generated by Django 4.1.5 on 2023-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0013_remove_products_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='image/%Y')),
                ('img2', models.ImageField(upload_to='image/%Y')),
                ('img3', models.ImageField(upload_to='image/%Y')),
            ],
        ),
    ]
