# Generated by Django 4.1.5 on 2023-02-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0016_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
    ]
