# Generated by Django 4.1.5 on 2023-02-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0018_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp1.products'),
            preserve_default=False,
        ),
    ]
