# Generated by Django 4.1.5 on 2023-02-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0019_remove_products_img_image_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
