# Generated by Django 4.1.5 on 2023-02-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0022_remove_image_product_id_remove_shoe_size_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_40',
            new_name='f40',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_43',
            new_name='f43',
        ),
    ]
