# Generated by Django 4.1.5 on 2023-02-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0023_rename__40_shoe_size_f40_rename__43_shoe_size_f43'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_40_5',
            new_name='f40d5',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_41',
            new_name='f41',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_41_5',
            new_name='f41d5',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_42',
            new_name='f42',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_42_5',
            new_name='f42d5',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_44',
            new_name='f44',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_44_5',
            new_name='f44d5',
        ),
        migrations.RenameField(
            model_name='shoe_size',
            old_name='_45',
            new_name='f45',
        ),
    ]
