# Generated by Django 4.1.5 on 2023-03-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsContent', '0007_productsize_size_delete_shoe_size_productsize_size_and_more'),
        ('cart', '0003_remove_orderitem_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='size', to='productsContent.products'),
            preserve_default=False,
        ),
    ]
