# Generated by Django 4.1.5 on 2023-03-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsContent', '0007_productsize_size_delete_shoe_size_productsize_size_and_more'),
        ('cart', '0004_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='productsContent.products'),
        ),
    ]
